### ISSUE TITLE
Can't switch from Kovan back to main network

### ISSUE THREAD

**Issue by mriedijk** [aragon/issues#104]
Metemask does not allow to switch back from Kovan test network to main network.
![screen shot 2017-11-23 at 10 26 17 pm](https://user-images.githubusercontent.com/1386630/33198017-6300ad2e-d09d-11e7-8d16-d7ba3f546433.png)

**Comment by izqui** [comment]
Alpha only works on the testnet, changing to the mainnet is not allowed
