### ISSUE TITLE
Aragon Test Ether

### ISSUE THREAD

**Issue by biznessio** [aragon/issues#106]
Hey!
I'm hoping to learn more about the Aragon platform but can't get the test ether sent to my Metamask address through the Aragon application. Any help would be really appreciated!
Thanks!

my account is 0x2789247f7315cdbb0b35cb6122d091ba1913d396

**Comment by izqui** [comment]
Our faucet had run out of test eth. I have just sent you some

**Comment by biznessio** [comment]
Thank you
