### ISSUE TITLE
Transfer did not arrive

### ISSUE THREAD

**Issue by Kuhein** [aragon/issues#111]
Hi guys, 

I've sent some aragon to my destrop wallet (Meta mask)

It's been a few days and the money did not arrive in my wallet.

This is the Shapeshift transaction:
https://www.shapeshift.io/#/status/430128d3-aa78-4a86-8b74-8c244f29f8e4

And this is my account:
https://kovan.etherscan.io/address/0x64b169c34c9501aafe757f071631e7a2a4ea7d7c

Cheers!

**Comment by Kuhein** [comment]
What an useless ICo, 
Fak Aragon and Fak your inexistent support service,
Im just glad I did a test payment first otherwise I would have lost all my bitcoin in your useless service.

Stay away from Aragon ppl.(they don't even have a support service), a bunch of amateurs.

**Comment by izqui** [comment]
The client you are using is not a wallet and it works only on the testnet. You cannot send real funds to it. If you copied the seed phrase from metamask on setup, you can import that in Metamask in Chrome and move your tokens in the mainnet.
