### ISSUE TITLE
Cannot receive Ether

### ISSUE THREAD

**Issue by Acoma78** [aragon/issues#51]
I cannot finish the registration process because I do not receive Ether. Even if I apply with my address on the faucet, the faucet confirms transaction, but Aragon does not show the transaction. --> I cannot press the "Continue" button.

**Comment by cbpr017** [comment]
I also have this issue.

**Comment by aargent** [comment]
For a company that has raised $250 million dollars a few days ago I find it ridiculous that the app has this simple bug and no one has responded for 24 hours!

I bet the investors are happy!! haha

**Comment by izqui** [comment]
Our faucet has ran out of test ether due to very high demand and we have been very busy. Getting some ether and it will resume working.

Also @aargent, you should check your numbers.

**Comment by izqui** [comment]
we have funded the faucet again, try now :)
