### ISSUE TITLE
Cannot setup wallet

### ISSUE THREAD

**Issue by cbpr017** [aragon/issues#52]
When setting up wallet, it cannot read the test ether that has been generated.

**Comment by izqui** [comment]
Our faucet has ran out of test ether due to very high demand and we have been very busy. Getting some ether and it will resume working.

**Comment by izqui** [comment]
we have funded the faucet again, try now :)

**Comment by Barukimang** [comment]
Hi. The MM 'get test eth' button doesn't see to work
