### ISSUE TITLE
Cannot get past first stage "continue"

### ISSUE THREAD

**Issue by aargent** [aragon/issues#54]
When opening app at the beginning there is 0 eth and even when manually clicking the link to generate eth on th test net no eth is generated.

Consequently one cannot continue to the next stage of configuration of Aragon.

**Comment by izqui** [comment]
Our faucet has ran out of test ether due to very high demand and we have been very busy. Getting some ether soon and it will resume working.

**Comment by izqui** [comment]
we have funded the faucet again, try now :)
