### ISSUE TITLE
Unable to use Aragon. Link to incorrect testnet faucet.

### ISSUE THREAD

**Issue by ignatov2** [aragon/issues#55]
I installed Aragon. Aragon includes MetaMask, running the Kovan test network. However, the "faucet" link on the main screen is for the Ropsten test network.

There is no automated faucet for Kovan test network, so I an unable to use Aragon.

**Comment by izqui** [comment]
Our faucet has ran out of test ether due to very high demand and we have been very busy. Getting some ether and it will resume working.

Also @aargent, you should check your numbers.

**Comment by izqui** [comment]
we have funded the faucet again, try now :)
