### ISSUE TITLE
exchanged money from Bitcoin to Desktop waller.. but nothing showing up.. pls check

### ISSUE THREAD

**Issue by chandraprakashmn** [aragon/issues#60]
Hi Team,
I have exchanged 370 dollar worth Bitcoin to Aragon using shapeshift.. i see the transaction completed.. but when i check i dont see any thing in my wallet. please help.

below is the Transaction ID screen.. Also my email ID is chandraprakash.mn@gmail.com.. please help

https://shapeshift.io/#/status/ba078363-1730-49b1-bf27-bb5d63add2ef

I have raised another request.. in Aragon issues page.. no response yet.. please respond to people if you are  working on the issue.

**Comment by onbjerg** [comment]
Hi @chandraprakashmn! I responded to you in your other issue (#58). Please have a look 🎉

**Comment by Smokyish** [comment]
Answered on issue #58
