### ISSUE TITLE
I have multiple companies - how do I log out from Aragon Mac desktop app?

### ISSUE THREAD

**Issue by stefek99** [aragon/issues#66]

**Comment by izqui** [comment]
Settings (click your avatar) > Unlink company

We need a better solution for this

**Comment by stefek99** [comment]
I suggest Slack-like interface to switch between companies.

![image](https://cloud.githubusercontent.com/assets/249703/26742135/57031b4e-47d4-11e7-9c4d-57f64087b22a.png)
