### ISSUE TITLE
Install Fail Windows 64 bit Vista

### ISSUE THREAD

**Issue by iotappman** [aragon/issues#76]
The result of Aragon.exe trying to install...

![image](https://user-images.githubusercontent.com/16193878/27195007-db5e0338-51d2-11e7-83c9-3c49d83cbdf0.png)

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Aragon.exe
  Application Version:	0.3.0.0
  Application Timestamp:	5880f159
  Fault Module Name:	SHELL32.dll!GetCurrentProcessExplicitAppUse
  Fault Module Version:	6.0.6002.19623
  Fault Module Timestamp:	56ec4641
  Exception Code:	c0000139
  Exception Offset:	00000000000b7e68
  OS Version:	6.0.6002.2.2.0.256.1
  Locale ID:	1033
  Additional Information 1:	fa3e
  Additional Information 2:	ac0507478d1c5bd693cfc4fe3987e900
  Additional Information 3:	fa3e
  Additional Information 4:	ac0507478d1c5bd693cfc4fe3987e900

**Comment by harshjv** [comment]
The Aragon dApp is shipped with Electron which doesn't support Vista.

You can check supported platforms here: https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md

@luisivan we should add supported platform somewhere in the readme.

**Comment by luisivan** [comment]
@harshjv agree -- wanna do it?
