### ISSUE TITLE
Unable to get Testnet Ether to my address

### ISSUE THREAD

**Issue by dclancy13** [aragon/issues#80]
Hey!
I really want to learn how to use the Aragon platform but can't get the test ether sent to my Metamask address through the Aragon application. Could you help?
Thanks!

my account is 0xe2b4265e9aac5735a53c05f21560b101f02d12a8

**Comment by luisivan** [comment]
@dclancy13 sent you 5!

**Comment by enkhee1117** [comment]
I cannot seem to get testnet ether for aragon either. 0x3A8825D1b63e882c78312984aEe3429AaA82773E
is the address. Thank you
