### ISSUE TITLE
Changing a bylaw requirement then changing bylaw type doesn't update UI correctly

### ISSUE THREAD

**Issue by Arachnid** [aragon/issues#95]
1. Select a bylaw type
2. Select a different action requirement
3. Select a different bylaw type
4. The newly selected bylaw type has the action requirement from 2, but the UI for the actual current action.

**Comment by onbjerg** [comment]
Hi @Arachnid! Thanks for your interest in Aragon 😊 

I'm going to close this since we're doing a complete refactor of everything - the client and the contracts, so this issue will not be current when 0.5 is released.

@izqui If you don't agree you can reopen this issue 💃
